# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 03:00
from __future__ import unicode_literals

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x8f\x91\xe5\xb8\x83\xe6\x97\xb6\xe9\x97\xb4')),
                ('text', models.TextField(verbose_name=b'\xe6\xad\xa3\xe6\x96\x87')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=blog.models.post_banner_upload_path, verbose_name=b'\xe5\x9b\xbe\xe7\x89\x87')),
                ('video', models.FileField(blank=True, null=True, upload_to=b'video')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe4\xbd\x9c\xe8\x80\x85')),
            ],
            options={
                'verbose_name': '\u535a\u5ba2',
                'verbose_name_plural': '\u535a\u5ba2',
            },
        ),
        migrations.CreateModel(
            name='PostComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=140, verbose_name=b'\xe8\xaf\x84\xe8\xae\xba')),
                ('corresponding_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='blog.Post')),
                ('corresponding_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u535a\u5ba2\u8bc4\u8bba',
                'verbose_name_plural': '\u535a\u5ba2\u8bc4\u8bba',
            },
        ),
    ]
