# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 02:24
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160729_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=blog.models.post_video_upload_path, verbose_name=b'\xe8\xa7\x86\xe9\xa2\x91'),
        ),
    ]
